import { useState } from 'react';
import { 
  useAttachments, 
  useQuarantineAttachment 
} from '../store/store';
import { 
  FileText, 
  ShieldAlert, 
  ShieldCheck, 
  AlertTriangle, 
  Archive, 
  CheckCircle2
} from 'lucide-react';

export default function AttachmentSecurity() {
  const attachments = useAttachments();
  const quarantineAttachment = useQuarantineAttachment();
  const [selectedAttId, setSelectedAttId] = useState<string | null>(attachments[0]?.id ?? null);
  const selectedAtt = attachments.find(att => att.id === selectedAttId) ?? attachments[0] ?? null;
  const [actionNotice, setActionNotice] = useState<string | null>(null);


  const latestSimulatedAttachment = attachments.find(att => att.id.startsWith('att-sim-'));

  const handleQuarantine = (attId: string) => {
    quarantineAttachment(attId);
    const nextAttachment = attachments.find(att => att.id !== attId && att.decision !== 'QUARANTINED');
    if (nextAttachment) setSelectedAttId(nextAttachment?.id ?? null);
    setActionNotice(`Payload ${attId} placed into simulated quarantine vault.`);
    setTimeout(() => setActionNotice(null), 3500);
  };

  return (
    <div className="space-y-6 animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* Header */}
      <div>
        <h1 style={{ fontSize: '1.75rem', fontWeight: 800, color: 'var(--text-primary)', letterSpacing: '-0.02em' }}>
          Attachment Security & Inspection
        </h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', marginTop: '0.2rem' }}>
          Safe static metadata inspection of inbound healthcare attachments and nested archive structures.
        </p>
      </div>

      {latestSimulatedAttachment && latestSimulatedAttachment.id === attachments[0]?.id && (
        <div className="card animate-fade-in" style={{
          padding: '1rem 1.25rem',
          background: 'linear-gradient(135deg, rgba(239,68,68,0.07), rgba(2,132,199,0.05))',
          border: '1px solid rgba(239,68,68,0.28)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '1rem',
          flexWrap: 'wrap',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <div style={{ width: 38, height: 38, borderRadius: 10, background: 'var(--critical-bg)', color: 'var(--critical)', display: 'grid', placeItems: 'center' }}>
              <ShieldAlert size={19} />
            </div>
            <div>
              <div style={{ fontSize: '0.72rem', fontWeight: 800, color: 'var(--critical)', letterSpacing: '0.06em' }}>NEW ATTACHMENT SIGNAL</div>
              <div style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--text-primary)' }}>{latestSimulatedAttachment.filename}</div>
              <div style={{ fontSize: '0.76rem', color: 'var(--text-secondary)' }}>Generated by phishing simulation • static metadata inspection required</div>
            </div>
          </div>
          <span className="badge bg-critical-light">RISK {latestSimulatedAttachment.riskScore}/100</span>
        </div>
      )}

      {/* Safety Notice */}
      <div style={{
        padding: '1rem 1.25rem',
        backgroundColor: 'var(--positive-bg)',
        border: '1px solid var(--positive)',
        borderRadius: '10px',
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
        fontSize: '0.85rem',
        color: 'var(--text-primary)',
      }}>
        <ShieldCheck size={20} color="var(--positive)" style={{ flexShrink: 0 }} />
        <div>
          <strong>Safe Synthetic Demonstration:</strong> CareSentinel performs non-detonative metadata heuristics and structural archive inspection without executing dangerous code or opening live exploits.
        </div>
      </div>

      {actionNotice && (
        <div style={{
          padding: '0.75rem 1.25rem',
          backgroundColor: 'var(--positive-bg)',
          border: '1px solid var(--positive)',
          color: 'var(--positive)',
          borderRadius: '8px',
          fontSize: '0.85rem',
          fontWeight: 600,
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem',
        }}>
          <CheckCircle2 size={16} /> {actionNotice}
        </div>
      )}

      {/* 2-Column Inspector */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))', gap: '1.5rem', alignItems: 'flex-start' }}>
        {/* Left: Attachment Selector List */}
        <div className="card" style={{ padding: '1.5rem', backgroundColor: 'white' }}>
          <h2 style={{ fontSize: '1.15rem', fontWeight: 700, marginBottom: '1rem', color: 'var(--text-primary)' }}>
            Inbound Clinical Attachments ({attachments.length})
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
            {attachments.map(att => {
              const active = selectedAtt?.id === att.id;
              const isDanger = att.riskScore >= 70;
              return (
                <button
                  key={att.id}
                  onClick={() => setSelectedAttId(att.id)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    padding: '0.85rem 1rem',
                    borderRadius: '8px',
                    border: active ? '1.5px solid var(--accent-primary)' : '1px solid var(--border)',
                    backgroundColor: active ? 'rgba(2, 132, 199, 0.05)' : 'var(--bg-main)',
                    textAlign: 'left',
                    transition: 'all 0.15s ease',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                    <div style={{
                      backgroundColor: 'white',
                      padding: '0.5rem',
                      borderRadius: '6px',
                      border: '1px solid var(--border)',
                      color: isDanger ? 'var(--critical)' : 'var(--accent-primary)',
                    }}>
                      {att.extension === '.zip' ? <Archive size={18} /> : <FileText size={18} />}
                    </div>
                    <div>
                      <div style={{ fontSize: '0.875rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                        {att.filename}
                      </div>
                      <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                        {att.size} • Uploaded by {att.sender}
                      </div>
                    </div>
                  </div>

                  <DecisionBadge status={att.decision === 'QUARANTINED' ? 'quarantined' : att.decision === 'SUSPICIOUS' ? 'pending' : 'allowed'} />
                </button>
              );
            })}
          </div>
        </div>

        {/* Right: Metadata & Heuristic Inspection Panel */}
        <div className="card" style={{ padding: '2rem', backgroundColor: 'white' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.5rem', borderBottom: '1px solid var(--border)', paddingBottom: '1rem' }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '.5rem', flexWrap: 'wrap', marginBottom: '.35rem' }}>
                <DecisionBadge status={selectedAtt.decision === 'QUARANTINED' ? 'quarantined' : selectedAtt.decision === 'SUSPICIOUS' ? 'pending' : 'allowed'} />
                <span className={`badge ${selectedAtt.riskScore >= 70 ? 'bg-critical-light' : 'bg-positive-light'}`}>
                  RISK: {selectedAtt.riskScore}/100
                </span>
              </div>
              <h2 style={{ fontSize: '1.35rem', fontWeight: 800, color: 'var(--text-primary)' }}>
                {selectedAtt.filename}
              </h2>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '0.2rem' }}>
                Inbound source: {selectedAtt.sender}
              </div>
            </div>

            {selectedAtt.decision !== 'QUARANTINED' ? (
              <button
                onClick={() => handleQuarantine(selectedAtt.id)}
                className="btn btn-danger"
                style={{ fontSize: '0.8rem', padding: '0.5rem 1rem' }}
              >
                <ShieldAlert size={15} /> Quarantine Payload
              </button>
            ) : (
              <div className="badge bg-critical-light" style={{ padding: '0.4rem 0.8rem' }}>
                VAULT ISOLATED
              </div>
            )}
          </div>

          {/* Metadata Specifications Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem', marginBottom: '1.5rem' }}>
            <div style={{ padding: '0.75rem', backgroundColor: 'var(--bg-main)', borderRadius: '8px', border: '1px solid var(--border)', fontSize: '0.825rem' }}>
              Detected File Type: <strong style={{ color: 'var(--text-primary)', display: 'block', marginTop: '2px' }}>{selectedAtt.detectedType}</strong>
            </div>
            <div style={{ padding: '0.75rem', backgroundColor: 'var(--bg-main)', borderRadius: '8px', border: '1px solid var(--border)', fontSize: '0.825rem' }}>
              Payload Size: <strong style={{ color: 'var(--text-primary)', display: 'block', marginTop: '2px' }}>{selectedAtt.size}</strong>
            </div>
            <div style={{ padding: '0.75rem', backgroundColor: 'var(--bg-main)', borderRadius: '8px', border: '1px solid var(--border)', fontSize: '0.825rem' }}>
              Archive Depth: <strong style={{ color: 'var(--text-primary)', display: 'block', marginTop: '2px' }}>{selectedAtt.archiveDepth} levels</strong>
            </div>
            <div style={{ padding: '0.75rem', backgroundColor: 'var(--bg-main)', borderRadius: '8px', border: '1px solid var(--border)', fontSize: '0.825rem' }}>
              Nested Files Count: <strong style={{ color: 'var(--text-primary)', display: 'block', marginTop: '2px' }}>{selectedAtt.nestedFilesCount} files</strong>
            </div>
            <div style={{ padding: '0.75rem', backgroundColor: 'var(--bg-main)', borderRadius: '8px', border: '1px solid var(--border)', fontSize: '0.825rem' }}>
              Compression Ratio: <strong style={{ color: selectedAtt.compressionRatio === 'HIGH' ? 'var(--critical)' : 'var(--positive)', display: 'block', marginTop: '2px' }}>{selectedAtt.compressionRatio}</strong>
            </div>
            <div style={{ padding: '0.75rem', backgroundColor: 'var(--bg-main)', borderRadius: '8px', border: '1px solid var(--border)', fontSize: '0.825rem' }}>
              Executable Content: <strong style={{ color: selectedAtt.executableContent ? 'var(--critical)' : 'var(--positive)', display: 'block', marginTop: '2px' }}>{selectedAtt.executableContent ? 'DETECTED' : 'NONE'}</strong>
            </div>
          </div>

          {/* Cryptographic Hash */}
          <div style={{
            padding: '0.85rem',
            backgroundColor: 'var(--bg-main)',
            borderRadius: '8px',
            border: '1px solid var(--border)',
            marginBottom: '1.5rem',
            fontSize: '0.8rem',
          }}>
            <div style={{ color: 'var(--text-muted)', fontWeight: 600, marginBottom: '0.2rem' }}>SHA-256 Checksum:</div>
            <div style={{ fontFamily: 'monospace', color: 'var(--text-primary)', wordBreak: 'break-all', fontSize: '0.75rem' }}>
              {selectedAtt.hash}
            </div>
          </div>

          {/* Script Indicators & Findings */}
          <div>
            <h3 style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '0.6rem', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              Inspection Findings
            </h3>
            {selectedAtt.executableContent ? (
              <div style={{
                padding: '0.85rem',
                backgroundColor: 'var(--critical-bg)',
                borderRadius: '8px',
                border: '1px solid rgba(239, 68, 68, 0.3)',
                display: 'flex',
                alignItems: 'flex-start',
                gap: '0.75rem',
                fontSize: '0.825rem',
                color: 'var(--critical)',
              }}>
                <AlertTriangle size={18} style={{ flexShrink: 0, marginTop: '2px' }} />
                <div>
                  <strong>Suspicious Executable & Macro Scripts Detected:</strong> This archive contains recursive directories with concealed executable binaries (.vbs / .exe) and abnormal compression density characteristic of ransomware loaders.
                </div>
              </div>
            ) : (
              <div style={{
                padding: '0.85rem',
                backgroundColor: 'var(--positive-bg)',
                borderRadius: '8px',
                border: '1px solid var(--positive)',
                display: 'flex',
                alignItems: 'flex-start',
                gap: '0.75rem',
                fontSize: '0.825rem',
                color: 'var(--positive)',
              }}>
                <CheckCircle2 size={18} style={{ flexShrink: 0, marginTop: '2px' }} />
                <div>
                  <strong>Clean Document:</strong> Verified PDF structure with valid clinical digital signature and no active JavaScript streams.
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
